# Generated by Django 2.2 on 2019-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='e_mail',
            field=models.CharField(blank='False', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='nick_name',
            field=models.CharField(blank='False', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='number_phone',
            field=models.IntegerField(blank='False', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank='False', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password_confir',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
