# Generated by Django 2.2 on 2019-06-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190603_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_confir',
        ),
    ]
