# Generated by Django 2.2 on 2019-06-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank='False', max_length=50, null='False')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(blank='False', max_length=100)),
                ('age', models.IntegerField()),
                ('e_mail', models.CharField(blank='False', max_length=50)),
                ('number_phone', models.IntegerField(blank='False', null='True')),
                ('github', models.CharField(max_length=50)),
                ('Student_Mentor', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
                ('is_mentorizing', models.BooleanField(default=False)),
            ],
            bases=('user.user', models.Model),
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
                ('is_working', models.BooleanField(default=False)),
            ],
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Program')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Mentor')),
                ('studentA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentA', to='user.Student2')),
                ('studentB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentB', to='user.Student2')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Course')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student2')),
            ],
        ),
    ]
